- packages/polymath-auth/.vscode/settings.json
- packages/polymath-investor/.vscode/settings.json
- packages/polymath-issuer/.vscode/settings.json
- packages/polymath-js/.vscode/settings.json
- packages/polymath-offchain/.vscode/settings.json
- packages/polymath-scripts/.vscode/settings.json
- packages/polymath-ui/.vscode/settings.json
This PR adds the pathToFlow workspace setting to each package individually, to enable flow when opening an individual package in the editor
> chore: add flow path to workspace settings of all packages

- README.md
Add instructions to get an account with ETH for development.
> doc: add dev instructions in README

- packages/polymath-investor/config/paths.js
- packages/polymath-investor/config/webpack.config.prod.js
- packages/polymath-investor/config/workspaceUtils.js
- packages/polymath-investor/package.json
- packages/polymath-investor/scripts/build.js
- yarn.lock
+ update build code as it's a major version.
This is related to this error: `Error: Cannot find module 'react-dev-utils/workspaceUtils'` happening on PR pipelines (for ex [see this build](https://dev.azure.com/polymathnetwork/polymath-apps/_build/results?buildId=936&view=logs)).
> build(investor): add missing react-dev-utils package

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
This PR adds documentation about our contribution guidelines.
* Moves contribution guidelines into its own file
* Adds more detail about our current agreements as a team
* Describes our continuous deployment setup
* Adds PR templates (Not for issues yet since we need the Unito integration to know how that's gonna look)
Please be sure to share here any concerns, things you disagree with and things that could be missing. These are guidelines we want to commit to follow so let's be sure to agree on them and revisit them in the future.
**NOTE: Since these are Markdown files you can click on the "View" button in the file changes to read it more easily**
> docs: add contribution guidelines

- packages/polymath-offchain/src/startup/__tests__/setupWeb3.js
- packages/polymath-offchain/src/startup/setupWeb3.js
A Web3 implementation mistake causes some socket error events to pass the error to the callback, and others to simply log it to the console directly without passing them to the callback. I simply fixed it
> fix(offchain): don't log errors that are not defined

- packages/polymath-offchain/.gitignore
- packages/polymath-offchain/package.json
This PR ignores tests in the /build folder and makes it so that test results are reported to the console as well as the other reporters. It also ignores junit.xml from being commited to the repo
> chore(offchain): ignore build tests, restore console reporting

- packages/polymath-ui/src/styles/globals.scss
Ugly hack cause of Carbon component structure.
> fix(issuer): position properly select component carret

- packages/polymath-shared/src/__tests__/constants.js
- packages/polymath-shared/src/constants.js
Uses different addresses for kovan on production vs kovan on staging
- Adds new addresses for a staging version of the contracts on kovan (deployed already)
- Adds tests to ensure we never mistakenly paste some production address into staging
Notes: Local is using Staging Kovan addresses for now, we can deploy a separate version if we need one (which we probably will soon. But I'm guessing its gonna happen with 2.0)
> feat(shared): use kovan staging addresses

- packages/polymath-shared/package.json
This fixes problems caused by Metamask caching some blockchain responses (which was responsible for POLY not being updated when using the local faucet)
> fix(shared): add 1 second blocktime to ganache-cli

- packages/polymath-issuer/.env.local
- packages/polymath-offchain/.env.local
- packages/polymath-offchain/src/__tests__/constants.js
- packages/polymath-offchain/src/constants.js
- packages/polymath-offchain/src/startup/__tests__/setupWeb3.js
- packages/polymath-offchain/src/startup/index.js
- packages/polymath-offchain/src/startup/setupWeb3.js
- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
- packages/polymath-ui/src/components/EthNetworkWrapper/networks.js
This PR adds support for local blockchains in offchain staging for testing purposes. It also reworks the offchain websocket reconnection logic. 
Offchain now differentiates between mandatory and optional networks depending on deployment stage. Mandatory networks retry the initial connection attempt on setup 5 times and optional networks don't retry (`CRITICAL_RETRIES = 5` vs `OPTIONAL_RETRIES = 0` defined in `constants.js`). When an initial connection attempt surpasses the retry limit, it will throw an error and exit (mandatory network) or simply log a warning (optional network). Once the initial connection has been established, if something happens to the websocket later, it will keep trying to …
> Support local blockchain in staging offchain

- packages/polymath-js/src/contracts/PolyToken.js
The metamask provider has caching issues and sometimes returns stale data when querying the blockchain, this caused a bug when using the local blockchain that didn't update the issuer's balance after certain transactions.
> Use websocket provider to fetch balance

- packages/polymath-offchain/.babelrc.js
This PR addresses unit tests failing in offchain if shared was not built previously. The babel config was resolving all root imports to `<package>/build` in offchain, even when testing (which shouldn't need other packages to be built).
> build(offchain): add src module resolver override for tests

- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
The dApps need to poll the current node through the provider to check for account/network changes in order to reload. Metamask suggested polling the node every 100ms. This, of course, is utterly insane. Some versions of chrome are sensible enough to throttle this insanity, but firefox received the full brunt of this onslaught of requests and produced weird behavior (even causing errors and crashes in ganache-cli). I suspect this might have been causing some other issues as well. I changed the polling interval to 1 second (which may be slower to detect a network or account change but at least it won't crash the user's browser). This fixes erratic behavior in firefox and possibly other …
> fix(ui): set account and network polling interval to 1 second

- packages/polymath-issuer/src/components/Dashboard.js
- packages/polymath-js/src/contracts/TickerRegistry.js
This fix isn't definitive. The problem is that when fetching the token while loading the providers page, sometimes the token doesn't exist, and sometimes it's simply not found in the blockchain at the moment of fetching. The second **SHOULD** never happen, since we only navigate naturally to the providers page after the transactions have been completed. This leads me to believe the issue is with the metamask provider and its ridiculous caching strategies. The proposed fix uses the web3 websocket provider to fetch the token details, but it's not 100% reliable since I can't reproduce the bug. The definitive fix would be to use the upcoming middleware to store registered tickers off-chain, so then if …
> fix: attempt to fix 404 error on providers page

- packages/polymath-ui/src/components/inputs/PercentageInput/index.js
This PR fixes empty values being shown as NaN in percentage inputs
> fix(ui): fix display value of percentage input when empty

- packages/polymath-issuer/src/components/App.js
- packages/polymath-issuer/src/components/AuthWrapper.js
As a ref here is the original issue:
> Steps to Reproduce (incl. in Production)
> - Navigate to a token-specific url (e.g. localhost:3000/dashboard/TEST-XXX)
> - Change to a metamask account that doesn't hold an account with Polymath (e.g. didn't register and verify her/his email)
> - Sign and create an account
> 
> Actual Result
> After creating an account you're redirected to a 404 page.
> 
> Expected Result
> You should be shown the email verification screen.
> fix(issuer): redirect to /ticker on signin fail

- packages/polymath-ui/src/components/inputs/DatePickerInput/index.js
- packages/polymath-ui/src/deprecated/components/inputs/DatePickerInput.js
This PR disallows the entry of invalid (past) dates on datepickers for the CappedSTO and USDSTO forms
> fix(ui): disallow past dates on datepickers

- packages/polymath-issuer/config/env.js
Before this fix, .env.local was being loaded before .env, and since dotenv doesn't override previously set env vars, local env was trumping any other
This PR fixes https://app.asana.com/0/707624907350863/901001229644910/f
> fix(issuer): change loading order of env vars

- packages/polymath-issuer/src/pages/sto/components/STOOverview/views/USDTieredSTO/index.js
On STO overview, raised amount was unstyled + wrongly displayed:
> fix(issuer): fix styling of raise amount box

- packages/polymath-issuer/src/pages/token/TokenPage.js
- packages/polymath-issuer/src/pages/token/components/CompleteTokenForm.js
Cleanest way I found. Split the states. Other way was the `componentDidUpdate`, was easier, but was dirty.
> fix(issuer): split states of investors number for token creation

- packages/polymath-ui/src/components/inputs/CurrencySelect/Input/index.js
error message or other siblings elements displayed incorrectly otherwise.
This PR solves this:
Note: this is intended to be a hotfix. So this should be merge in both `master` and `develop`. Or we can cherry-pick later otherwise, depending on how we want to do!
> fix(ui): add a wrapping element on CurrencySelect

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/CappedSTO/index.js
- packages/polymath-issuer/src/utils/contracts/index.js
- packages/polymath-js/src/contracts/PolyToken.js
- packages/polymath-offchain/src/startup/setupWeb3.js
This PR:
- Fixes a bug caused by updating the local blockchain to 2.1 (there have been breaking changes in both STOs in the new contracts)
- Removes the workaround that fixed discrepancies in event parameter names between the PolyToken and PolytokenFaucet (in 2.1 they standardized the names)
**WARNING:** do NOT merge this PR if we plan to release in legacy before 2.1 is live in mainnet or STOs will break there. This fix should be only for local testing
> fix: adapt STO deployment to core 2.1

- packages/polymath-issuer/src/pages/sto/STOPage.js
- packages/polymath-issuer/src/pages/sto/components/STOOverview/views/USDTieredSTO/TiersTable.js
- packages/polymath-issuer/src/pages/sto/components/STOOverview/views/USDTieredSTO/index.js
- packages/polymath-issuer/src/reducers/sto.js
- packages/polymath-js/src/contracts/STO.js
- packages/polymath-js/src/types.js
Also fix progress bars (once again)
This PR fixes a bug where an issuer couldn't mint tokens even after an STO had been finished. It also fixes the STO overview progress bars being passed values between 0 and 1 instead of percentages, which caused them to look 1/100 of their actual size
> fix: enable minting after an STO has been completed

- packages/polymath-ui/src/components/TxModal/actions.js
Introduces a temporary hack to get route changes done. For some reason route changes through dispatch are broken unless they are dispatched twice. 
I apologize for the horrible fix, this is only a temporary fix to avoid having a release blocker for dividends. This should be revisited once the urgent tasks for dividends are ready.
(Note that this only on legacy)
> fix(issuer): hacky fix for programatically changing routes

- packages/new-polymath-issuer/src/components/DividendCard/DividendCard.tsx
- packages/new-polymath-issuer/src/components/DividendList/Container.tsx
- packages/new-polymath-issuer/src/components/DividendList/Presenter.tsx
This PR:
- Displays actual data in the Dividend Card and fixes the "View Details" button
- Disables the "add new dividend distribution" button if the previous distribution hasn't been completed
> fix(new-issuer): use actual data in the dividend card

- packages/new-polymath-issuer/src/pages/DividendsWizard/Presenter.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/TaxWithholdingModal.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
This PR uses the investors who actually hold tokens to calculate the numbers in the summary box
> fix(new-issuer): use actual tokenholders to calculate amounts

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/TaxWithholdingModal.tsx
"'New' or 'Updated' won't be displayed if adding the same investor twice in dividends step 2"
> fix(new-issuer): do not delete label if investor already exists

- packages/new-polymath-ui/src/components/inputs/PercentageInput/PercentageInput.tsx
Fixes the bug: [Inputting two decimals in the dividends step two translates into a long decimal](https://app.asana.com/0/951808452757493/1114871323437269)
> fix(new-ui): decimals in percentage input

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-3/index.tsx
- packages/new-polymath-sdk/src/LowLevel/PolyToken.ts
- packages/new-polymath-sdk/src/procedures/Approve.ts
This PR:
- Adds validation to step 3 of the wizard to prevent the issuer from requesting more than 1M POLY from the faucet (which would otherwise revert because of validation in the contract)
- Properly converts the amount passed to getTokens to wei in the SDK
- Properly checks if the issuer has enough balance before checking if they have already approved the funds (you can technically approve amounts you don't own so you could in theory have enough approval but not enough funds)
- Rounds up the required funds from the faucet to the nearest integer (this isn't a requirement but it doesn't hurt and makes the display in the Tx modal easier on the eyes in case the issuer has a balance with too many …
> fix: request correct amount from faucet and add faucet validation

- packages/new-polymath-issuer/src/components/DividendCard/DividendCard.tsx
- packages/new-polymath-issuer/src/components/DividendCard/styles.ts
- packages/new-polymath-ui/src/components/Heading/Heading.tsx
Fixes: 
[Text is not wrapped on the dividends title in the dividends screen](https://app.asana.com/0/427839295975995/1115263376778652)
> chore(new-ui): add word wrap to dividend card heading

- packages/new-polymath-issuer/src/pages/DividendDetails/Presenter.tsx
- packages/new-polymath-ui/src/components/utils/contentMappings.ts
Also fixed the tx modal language when the payment fails and there is only one transaction
> fix: fix completed transaction percentage when there are no tokenholders

- packages/polymath-issuer/src/pages/sto/components/STOOverview/views/USDTieredSTO/index.js
Fixes: [USD Tiered STO 'Closed' screen still shows countdown](https://app.asana.com/0/951808452757493/1115358725913804)
> fix(issuer): ensure countdown disappears when sto is closed

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-1/index.tsx
Fixes the issue [Dividends step 1 import doesn't enforce the headers](https://app.asana.com/0/951808452757493/967385233474295)
CSV file is marked as `strict` to prevent extra headers.
> fix(new-issuer): dividends step 1 enforce headers

- packages/new-polymath-ui/src/components/CsvUploader/CsvErrors/index.tsx
Fixes the issue [Dividends step 1 import doesn't enforce the headers](https://app.asana.com/0/951808452757493/967385233474295)
Previously, the CSV uploader was showing a warning if the file has extra columns, this is changed to error as bellow:
> fix(new-ui): display error if csv has extra columns

- packages/new-polymath-issuer/src/pages/DividendsWizard/Presenter.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
Fixes the bug [Issuer gets no warning when navigating backwards from dividends step 2 to dividends step 1 while having not submitted investors](https://app.asana.com/0/951808452757493/1115263376778667)
If there are transactions that are not posted to the blockchain:
- If the user clicks on `GO BACK` from the wizard, the modal confirm will be displayed.
- If the user clicks on the `refresh` button on the browser or types in a new URL, a native confirm modal will be shown, the text of this modal can not be customized as per [this reference](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload#Notes). Support for custom text has been removed. So the message bellow will be …
> fix(new-issuer): confirm unposted transactions

- packages/new-polymath-issuer/src/pages/DividendsWizard/Container.tsx
Fixes the issue: [Error when issuer tries to access a dividend checkpoint id that doesn't exist](https://app.asana.com/0/951808452757493/1116505368895676)
> fix(new-issuer): url access to non-existing checkpoint

- packages/new-polymath-issuer/src/pages/DividendsWizard/Presenter.tsx
Fixes the issue [Issuer warned about changes when going back from step 3](https://app.asana.com/0/951808452757493/1116781223885769)
> fix(new-issuer): step 3 back warning

- packages/new-polymath-ui/src/components/Modal/Modal.tsx
- packages/new-polymath-ui/src/styles/GlobalStyles.ts
This PR fixes a bug where the page was jumping when opening/closing a modal while the body doesn't have a scroll (content shorter than the viewport).
> fix(new-ui): fix body scroll lock jump when body doesnt scroll

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/TierModal.js
Fixes the issue [USD Tiered STO price gets stuck at 0.01](https://app.asana.com/0/951808452757493/1116970805613916)
The first fix took care of the `Single`, this PR fixes the same issue on the `Multiple` modal.
> fix(issuer): tiered sto multi price stuck at 0

- packages/polymath-issuer/src/routes.js
- packages/polymath-offchain/src/routes/providers.js
- packages/polymath-ui/src/components/ProvidersMaintenancePage/ProvidersMaintenancePage.js
- packages/polymath-ui/src/components/ProvidersMaintenancePage/index.js
- packages/polymath-ui/src/index.js
- Another attempt at catching and printing sendgrid errors.
- Added ProvidersMaintenancePage. To be used later if needed.
> fix: better error display + stage providers' maintenance page

- packages/polymath-js/src/contracts/Contract.js
Just added a catch-all exception handler. It will stop the spinner in case of exceptions in general, instead of just detecting and handling a few.
> Fix for forever running transactions after metamask rejection

- packages/polymath-js/src/contracts/TransferManager.js
While retrieving a whitelist, expiry date was mapped, incorrectly, to canReceiveAfter property.
> fix(issuer): fix a regression

- packages/polymath-issuer/src/actions/compliance.js
- packages/polymath-js/src/contracts/TransferManager.js
This is the last PR regarding csv import/export. It includes:
- Properly negate smart contract's `canNotBuyFromSTO` into dapp's `canBuyFromSTO`.
- Exclude `Exempt from %` from csv export if `percentageTM` module is paused.
> fix(issuer): fix the export of investor flags

- packages/polymath-issuer/src/pages/compliance/CompliancePage.js
Tacking those issues:
- "add 3rd party whitelist manager" should be: "add 3rd party whitelist manager*s*"
- "and manage approval of token transfer between wallets" should be "and manage approval of token transfer*s* between *particular*wallets."
- just noticed one more thing: please remove the space before the comma after "import and export your whitelist"
> GT-86: fix some typos
