PolymathNetwork/polymath-apps

- packages/polymath-ui/src/components/inputs/TextInput.js
- packages/polymath-ui/src/modules/account/SignUpForm.js
trim email using redux-form onchange to replace previous use of normalize and avoid cursor position changing
> fix(ui): fix trim email

- package.json
- packages/polymath-ui/src/components/inputs/TextInput.js
Adds pre-commit formatting hook (was not correctly configured).
> chore: add pre-commit code formatting

- packages/polymath-offchain/Procfile
Indicates what command to type to start the application on Heroku.
> chore(offchain): add Heroku Procfile

- packages/polymath-shared/scripts/utils.js
Log stdout on commands running in script
> chore(shared): log command outputs

- packages/polymath-shared/scripts/generateLocalBlockchain/index.js
- packages/polymath-shared/scripts/generateLocalBlockchain/steps.js
Fixes fixtures script, removes need to copy `build` folder
> build(shared): remove dependency to old copied files

- packages/polymath-offchain/.env.local
- packages/polymath-offchain/.env.test
- packages/polymath-offchain/README.md
- packages/polymath-offchain/src/constants.js
- packages/polymath-offchain/src/startup/setupDb.js
rename it to MONGODB_URI which is the popular choice
> fix(offchain): fix mongodb env var name

- packages/polymath-ui/src/components/Footer/Footer.js
remove usage of React Router as they are external links.
> fix(ui): fix footer links

- packages/polymath-shared/src/constants.js
This PR fixes issuer not being able to find the local contract addresses when in staging. It also adds support for the LocalVM network (id 16)
> fix(shared): export local addresses for staging

- packages/polymath-ui/src/components/Footer/__tests__/__snapshots__/Footer.js.snap
This is just forgotten snapshot updates for #125
> fix(ui): update footer snapshot after fix

- packages/polymath-issuer/src/pages/providers/ApplyForm.js
- packages/polymath-issuer/src/pages/providers/ApplyModal.js
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm.js
- packages/polymath-issuer/src/pages/ticker/components/TickerForm.js
- packages/polymath-issuer/src/pages/token/components/CompleteTokenForm.js
> fix(issuer): add mandatory and optional flags next to form fields

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
- packages/polymath-ui/package.json
Fixes the performance issues we are having in USDTieredSTO form.
- Uses `withFormik`
- Avoids extra re-renders through `shouldComponentUpdate`
- Avoids re-renders `onChange`, only `onBlur` re-renders form now
> perf(issuer): optimize USDTieredSTO form

- packages/polymath-issuer/src/utils/contracts/index.js
> refactor(shared): parallelize sto module fetches in contracts utils

- packages/polymath-issuer/src/pages/sto/style.scss
- packages/polymath-ui/src/styles/globals.scss
This is a cherry-pick from `epic/2.0-contracts`.
> fix(issuer): fix global layout broken on big width

- packages/polymath-offchain/src/emails/CappedSTOScheduled.js
- packages/polymath-offchain/src/emails/TickerReserved.js
- packages/polymath-offchain/src/emails/TokenCreated.js
- packages/polymath-offchain/src/emails/USDTieredSTOScheduled.js
- packages/polymath-offchain/src/emails/__tests__/CappedSTOScheduled.js
- packages/polymath-offchain/src/emails/__tests__/EmailWrapper.js
- packages/polymath-offchain/src/emails/__tests__/USDTieredSTOScheduled.js
- packages/polymath-offchain/src/emails/__tests__/__snapshots__/CappedSTOScheduled.js.snap
- packages/polymath-offchain/src/emails/__tests__/__snapshots__/USDTieredSTOScheduled.js.snap
- packages/polymath-offchain/src/emails/index.js
- packages/polymath-offchain/src/startup/__tests__/setupWeb3.js
- packages/polymath-offchain/src/startup/setupWeb3.js
- packages/polymath-offchain/src/utils/__tests__/emails.js
- packages/polymath-offchain/src/utils/emails.js
- packages/polymath-offchain/src/utils/index.js
Also fixed offchain tests
This PR adds a new (bare bones) email template for the USDTieredSTO to act as a placeholder until we get the design. It also implements the logic that sends said email. It also fixes a bunch of previously broken tests in offchain
> feat(offchain): add email template for USDTieredSTO

- packages/polymath-shared/src/utils/format.js
- yarn.lock
Unit tests doing their magic, caught this one
> fix(shared): number formatters crashing for BigNumber instances

- packages/polymath-ui/src/components/EthNetworkWrapper/EthNetworkWrapper.js
- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
> fix(ui): make sure user is privacy mode off before asking for permission

- packages/polymath-issuer/src/components/AuthWrapper.js
This PR fixes the email confirmation flow by asking for confirmation right after the issuer inputs his name and email, and BEFORE he can proceed with ticker registration (I'm not sure why it expected the user to already have registered a ticker before)
> fix(issuer): rework email confirmation flow

- packages/polymath-issuer/src/pages/compliance/CompliancePage.js
- packages/polymath-issuer/src/pages/compliance/style.scss
- packages/polymath-ui/src/styles/globals.scss
Conflicts:
packages/polymath-issuer/src/pages/compliance/CompliancePage.js
packages/polymath-ui/src/styles/globals.scss
> chore: fix css breaking after Carbon upgrade

- packages/polymath-issuer/src/pages/compliance/CompliancePage.js
- packages/polymath-issuer/src/pages/compliance/style.scss
- packages/polymath-shared/src/constants.js
- packages/polymath-ui/src/styles/globals.scss
> Fix styling bugs

- packages/polymath-issuer/src/actions/token.js
> fix(issuer): change tx order for creating token with limited investors

- packages/polymath-issuer/src/actions/sto.js
- packages/polymath-ui/src/redux/account/actions.js
Sets the default amount of POLY given by the faucet to `100,500 POLY`
> feat(ui): increase default poly given in faucet to 100,500 POLY

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
- packages/polymath-issuer/src/pages/sto/components/STOOverview/views/USDTieredSTO/index.js
- packages/polymath-ui/package.json
- packages/polymath-ui/src/components/ConfirmModal/ConfirmModal.js
- packages/polymath-ui/src/components/inputs/DatePickerInput/index.js
- packages/polymath-ui/src/deprecated/components/inputs/TextInput.js
- yarn.lock
- Fixes issue with timezone in start/end dates for USDTieredSTO config form
- Removes some errors from the console
- Other minor improvements
> fix(issuer): sto overview displaying wrong end date

- packages/polymath-issuer/src/pages/providers/data.js
Fixes the issue: Katipult has no 'more info' and incomplete text
> fix(issuer): modify description for Katipult

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/CappedSTO/index.js
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
Removed initial values from USDSTO form and autocomplete from CappedSTO form
> fix(issuer): remove initial values and disable autocomplete

- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
> fix(ui): increase polling interval from 100ms to 1s

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/InvestmentTiers.js
This PR fixes https://app.asana.com/0/847626103624930/905704600785461
> fix(issuer): display correct tier number in the add tier modal

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
> docs(issuer): add a comment explaining all fields having initialvalues

- packages/polymath-issuer/src/actions/sto.js
Exactly what is says on the tin
> Change the first Capped STO transaction's title to "Transferring POLY" 

- packages/polymath-issuer/src/style.scss
- packages/polymath-ui/src/components/inputs/DatePickerInput/index.js
> fix(ui): remove datepicker extra bottom spacing

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/AddTierModal.js
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/InvestmentTiers.js
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
- packages/polymath-ui/src/components/inputs/NumberInput/index.js
- Fixes input warnings coming from NumberInput
- Fixes some crashes where BigNumber type was lost
> fix: number input warnings

- packages/polymath-issuer/src/routes.js
- packages/polymath-ui/src/components/MaintenancePage/MaintenancePage.js
- packages/polymath-ui/src/components/MaintenancePage/MaintenancePage.mdx
- packages/polymath-ui/src/components/MaintenancePage/index.js
- packages/polymath-ui/src/components/NotFoundPage/NotFoundPage.js
- packages/polymath-ui/src/index.js
> feat: add /maintenance page

- packages/polymath-issuer/src/pages/token/components/MintTokens.js
> fix(issuer): remove warning about minting not available

- packages/polymath-issuer/src/actions/token.js
This PR fixes a language inaccuracy in the transaction modal for token deployment
> fix(issuer): make token creation transaction modal text more accurate

- packages/polymath-issuer/src/actions/compliance.js
This PR fixes a bug that prevented investor whitelists from being exported
> fix(issuer): fix faulty object deconstruction

- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
> chore(issuer): update copy of whitelist modal

- packages/polymath-issuer/src/constants.js
- packages/polymath-issuer/src/index.js
- packages/polymath-ui/package.json
- packages/polymath-ui/src/components/ErrorBoundary/ErrorBoundary.js
- yarn.lock
> feat: add Sentry support

- packages/polymath-issuer/src/routes.js
- packages/polymath-ui/src/components/MaintenancePage/MaintenancePage.js
- packages/polymath-ui/src/components/MaintenancePage/MaintenancePage.mdx
- packages/polymath-ui/src/components/MaintenancePage/index.js
- packages/polymath-ui/src/components/NotFoundPage/NotFoundPage.js
- packages/polymath-ui/src/index.js
> cherry-pick maintenance page to develop

- packages/polymath-issuer/src/pages/providers/ProvidersPage.js
- yarn.lock
> Fix issue "'Advisory' is marked automatically as 'I have my own'"

- packages/polymath-issuer/src/index.js
> fix(issuer): disable Sentry locally

- packages/polymath-issuer/src/pages/compliance/CompliancePage.js
- packages/polymath-issuer/src/pages/sto/components/STODetails.js
- packages/polymath-issuer/src/pages/token/TokenPage.js
- packages/polymath-issuer/src/pages/token/components/MintTokens.js
- packages/polymath-ui/src/components/NoticeBar/actions.js
> Release Maintenance mode page to production

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
> Indicate start time in datepicker validation errors

- packages/polymath-issuer/src/constants.js
> fix(issuer): update link for sto audits

- README.md
- packages/polymath-offchain/README.md
> docs: update READMEs (global and offchain)

- packages/polymath-shared/package.json
this was causing errors to be even less verbose than they usually are
> fix(shared): remove local blockchain blocktime parameter

- packages/polymath-offchain/README.md
- packages/polymath-offchain/src/__tests__/constants.js
- packages/polymath-offchain/src/constants.js
- packages/polymath-shared/package.json
- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
- packages/polymath-ui/src/components/EthNetworkWrapper/networks.js
This is an update to our test release branch to verify our deployment setup is working well
> Test release

- packages/polymath-issuer/src/actions/token.js
This PR fixes address and token symbol comparisons when checking if the issuer has a legacy token
> Freezing/renouncing ownership HOTFIX

- packages/polymath-issuer/src/actions/sto.js
> fix(issuer): add space to sto poly fee

- packages/polymath-ui/src/validate.js
> fix(ui): update email validation to only allow one + symbol

- packages/polymath-issuer/src/pages/token/components/CompleteTokenForm.js
> fix(issuer): limit characters in token information field

- packages/polymath-issuer/src/actions/compliance.js
> fix(issuer): fix typo on successful change of whitelist

- packages/polymath-issuer/src/pages/providers/data.js
> fix(issuer): fix provider name

- packages/new-polymath-scripts/README.md
- packages/new-polymath-scripts/src/populateLocalBlockchain/index.js
- packages/new-polymath-scripts/src/populateLocalBlockchain/seedData.json
- packages/new-polymath-scripts/src/populateLocalBlockchain/wallets.json
This PR abstracts the account addresses and private keys from the seed data json to make it easier to read and modify
> feat(polymath-scripts): make addresses more readable

- packages/polymath-issuer/src/pages/providers/data.js
> fix(issuer): update providers

- packages/polymath-ui/src/redux/account/actions.js
> fix(ui): fix faulty error condition

- packages/polymath-issuer/src/components/Dashboard.js
- packages/polymath-issuer/src/pages/dividends/DividendsPage.js
- packages/polymath-issuer/src/routes.js
- packages/polymath-ui/src/components/Sidebar/style.scss
- packages/polymath-ui/src/images/svg/dividends.js
- packages/polymath-ui/src/index.js
Add /dividends page on `polymath-issuer` app.
> feat(issuer): add new /dividends page

- packages/new-polymath-scripts/.babelrc.js
- packages/polymath-offchain/package.json
This PR adapts the offchain build to point to the new scripts package (where the artifacts currently reside)
> fix(offchain): fix build process

- packages/new-polymath-issuer/src/lib/__tests__/polyClient.ts
- packages/new-polymath-issuer/src/lib/polyClient.ts
> fix(new-issuer): fix faulty test

- packages/new-polymath-sdk/tsconfig.json
Minor fix to have proper typings and transforms in test files
> fix(sdk): consider tests in the config

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/CappedSTO/index.js
> fix(issuer): add decimals to rate field in capped sto

- packages/polymath-ui/src/components/MetamaskStatus/MetamaskStatus.js
- packages/polymath-ui/src/components/MetamaskStatus/status/GenericStatus.js
> fix(issuer): fix metamask logo overlap and adjust styles

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/InvestmentTiers.js
> fix(issuer): display decimals for tier token amounts

- packages/polymath-issuer/src/pages/token/components/MintTokens.js
> fix(issuer): disable minting when STO is in progress

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/InvestmentTiers.js
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/TierModal.js
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
> fix(issuer): resolve issue with sto failing due to small decimals

- packages/polymath-ui/src/components/inputs/NumberInput/index.js
> fix(issuer): handle pasted text with non-numeric characters

- packages/polymath-issuer/src/actions/compliance.js
- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
- packages/polymath-issuer/src/reducers/compliance.js
- packages/polymath-issuer/src/utils/parsers/index.js
> fix(issuer): display error when an invalid whitelist csv is uploaded

- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
> fix(issuer): reset file marker when invalid csv is removed

- packages/polymath-issuer/src/actions/token.js
- packages/polymath-issuer/src/pages/token/components/MintTokens.js
> fix(issuer): warn user if kyc expiry date has expired

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/CappedSTO/index.js
> fix(issuer): display 20 digits (with 6 decimals) in raised amount

- packages/polymath-issuer/src/pages/sto/components/STOOverview/views/CappedSTO.js
- packages/polymath-ui/src/components/STOStatus/STOStatus.js
> fix(issuer): fix ui overlap on cappedsto

- packages/polymath-issuer/src/pages/compliance/CompliancePage.js
> fix(issuer): disable changing max ownership if percentage is unchanged

- packages/polymath-issuer/src/utils/parsers/index.js
> [WIP] fix(issuer): make header row mandatory on whitelist

- packages/polymath-issuer/src/actions/compliance.js
- packages/polymath-js/src/contracts/TransferManager.js
> [WIP] Fix/whitelist stoheaders

- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
> fix(issuer): adjust whitelist modal text based on sto status

- packages/polymath-offchain/src/emails/EmailWrapper.js
> fix(offchain): send correct txHash link on mainnet for token creation

- packages/polymath-offchain/src/utils/emails.js
> fix(offchain): send a copy of provider emails to issuers

- packages/new-polymath-issuer/src/components/Header/Container.tsx
- packages/new-polymath-ui/src/components/Header/Header.tsx
> fix: fix typings

- packages/polymath-issuer/src/utils/parsers/index.js
> Revise parsing date in whitelist

- packages/polymath-issuer/src/pages/compliance/CompliancePage.js
> fix(issuer): restrict max ownership field to accept 1 to 100

- packages/polymath-issuer/src/actions/compliance.js
> chore(issuer): fix typo in whitelist transaction modal

- packages/polymath-ui/src/components/Countdown/Countdown.js
> chore(issuer): force page reload when sto countdown reaches 0

- packages/polymath-offchain/src/emails/CappedSTOScheduled.js
- packages/polymath-offchain/src/emails/__tests__/CappedSTOScheduled.js
- packages/polymath-offchain/src/emails/__tests__/__snapshots__/CappedSTOScheduled.js.snap
Note: We need to update offchain to `bignumber.js` v7 to support numbers bigger than 15 digits.
> Fix capped sto email using big number

- packages/polymath-issuer/src/pages/ticker/components/ReserveTickerForm.js
> fix(issuer): submit ticker symbol uppercase

- packages/polymath-issuer/src/actions/sto.js
> fix(issuer): check spent poly balance before asking for faucet

- packages/polymath-issuer/src/actions/token.js
> fix(issuer): ignore blank rows on minting csv

- packages/polymath-issuer/src/pages/sto/components/STOOverview/views/USDTieredSTO/index.js
This is WIP until issues with running USDSTO on localhost have been fixed
> [WIP] fix(issuer): pass whole number instead of fraction to progressbar

- packages/polymath-issuer/src/pages/sto/components/STOOverview/views/USDTieredSTO/index.js
Reverts PolymathNetwork/polymath-apps#325
> Revert "[WIP] fix(issuer): pass whole number instead of fraction to progressbar"

- packages/polymath-issuer/src/pages/token/components/MintTokens.js
> fix(issuer): remove invalid file marker when file is removed

- packages/polymath-issuer/config/env.js
- packages/polymath-issuer/package.json
- packages/polymath-issuer/src/components/Root.js
- packages/polymath-issuer/src/index.js
- packages/polymath-issuer/src/modernAdapters/polyClient.js
- packages/polymath-issuer/src/mountLegacy.js
- packages/polymath-issuer/src/mountModern.js
- packages/polymath-issuer/src/pages/dividends/DividendsPage.js
- packages/polymath-issuer/src/pages/dividends/index.js
- packages/polymath-issuer/src/redux/reducer.js
- packages/polymath-issuer/src/redux/store.js
- packages/polymath-issuer/src/specsInit.js
- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
- yarn.lock
- Adds the required configuration to allow our two methods for incorporating Mordern code into Legacy
- Plugs in Dividends into Legacy
> Feature/dividends  plug into legacy

- packages/polymath-ui/src/components/STOStatus/STOStatus.js
> fix(ui): update stostatus component to fill progressbar

- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
- packages/polymath-issuer/src/utils/parsers/index.js
> fix(issuer): display error if date in whitelist csv is valid

- packages/polymath-issuer/src/actions/sto.js
> chore(issuer): display sto fee with thousandsdelimiter

- packages/polymath-ui/src/components/STOStatus/STOStatus.js
> fix(ui): display if sale is complete in stostatus component

- packages/polymath-issuer/public/whitelist-sample.csv
- packages/polymath-issuer/src/actions/compliance.js
- packages/polymath-issuer/src/utils/parsers/index.js
- packages/polymath-issuer/testUtils/fixtures/csvFiles.js
> fix(issuer): improve header checking and fix sample

- packages/polymath-offchain/src/emails/EmailWrapper.js
> fix(offchain): fix the year in email footer

- packages/polymath-issuer/src/pages/ticker/components/ReserveTickerForm.js
Validate the following condition of the ticker:
- Ticker must start with a letter or number (and not with special characters)
- Ticker must end with a letter or number (and not with special characters)
- Ticker must not contain 2 special characters together
> fix(issuer): special characters validation

- packages/new-polymath-sdk/src/entities/Erc20DividendsModule.ts
> fix(issuer): crash when fetching dividends module

- packages/new-polymath-ui/src/components/utils/contentMappings.ts
This PR replaces the placeholder text for real text in all transactions related to dividends.
> feat(new-ui): add real text to dividend transactions

- packages/new-polymath-issuer/src/pages/SecurityTokensDividends/Container.tsx
- packages/new-polymath-issuer/src/pages/SecurityTokensDividends/Presenter.tsx
- packages/new-polymath-sdk/src/LowLevel/DividendCheckpoint.ts
- packages/new-polymath-sdk/src/Polymath.ts
- packages/new-polymath-sdk/src/entities/DividendsModule.ts
- packages/new-polymath-sdk/src/entities/Erc20DividendsModule.ts
- packages/new-polymath-sdk/src/entities/EthDividendsModule.ts
- packages/new-polymath-shared/src/typing/types.ts
This PR adds the storage wallet address to the dividends module entities returned by the SDK
> feat(sdk): add storage wallet address to dividends module entities

- packages/new-polymath-ui/src/validator/index.ts
> fix: add message to isEthereumaddres validation

- packages/new-polymath-issuer/src/components/CheckpointList/Container.tsx
- packages/new-polymath-shared/src/utils/index.ts
> fix(new-shared): ensure csv extension on csv downloads

- packages/polymath-issuer/src/routes.js
> fix(new-issuer): fix back-button broken on dividends wizard

- packages/new-polymath-ui/src/components/Page/Page.tsx
> feat(new-ui): make pages default to scrolling to top on mount

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
> refactor(new-issuer): remove unnecessary ternary

- packages/new-polymath-issuer/src/components/DividendList/Presenter.tsx
- packages/polymath-issuer/src/routes.js
> fix(issuer): regression of broken dividends button

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-1/index.tsx
> fix(issuer): update step 1 warning text

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
Fixes the bug (No input validation on edit a tax withholding investor)
https://app.asana.com/0/951808452757493/1113255342169342
> fix(new-issuer): dividends wizard step 2 validation

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
Fixes the bugs: 
- [Valid files are marked as incorrect on the dividends step 2 page](https://app.asana.com/0/951808452757493/1113387610066223).
- [Existing Withholding Tax List Step is automatically showing existing investors](https://app.asana.com/0/951808452757493/1113112873571166).
> fix(new-issuer): fix tax withholding upload

- packages/new-polymath-issuer/src/pages/DividendsWizard/Container.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Presenter.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-3/index.tsx
- packages/new-polymath-ui/src/components/Form/Form.tsx
> [WIP] fix(issuer): submit dividends form

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/TaxWithholdingsTable.tsx
- packages/new-polymath-ui/src/styles/theme.ts
> feat: add status pills for step 2 table

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-1/index.tsx
> chore(issuer): modify modal text for updating wallet exclusion list

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-1/index.tsx
> chore(new-issuer): notify issuer about expired kyc

- packages/new-polymath-issuer/src/components/ListIcon/index.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Presenter.tsx
> chore(new-issuer): modify background color for Listicons

- packages/new-polymath-ui/src/components/FileUploader/FileUploader.tsx
> chore(new-ui): modify fileuploader placeholder

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/CsvModal.tsx
> fix: csv uploader not displaying table or errors

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-3/index.tsx
- packages/new-polymath-ui/src/validator/schemas/BigNumberSchema.ts
> feat(new-issuer): add step3 validations

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/CsvModal.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/TaxWithholdingModal.tsx
> fix(new-issuer): updated files from csv marked as new

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/TaxWithholdingsTable.tsx
Fixes the bug [Update button is not disabled after update in dividends step 2](https://app.asana.com/0/951808452757493/1113838682012043)
> fix(new-issuer): disable update button after submit

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/CsvModal.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/TaxWithholdingsTable.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
Fixes the bug [Wizard Step 2: Separate withholding addresses into batches of 200 and use multiple transactions](https://app.asana.com/0/951808452757493/1113316555175847)
> fix(new-issuer): withholding addresses limit

- packages/polymath-issuer/src/components/Dashboard.js
- packages/polymath-ui/src/components/Sidebar/Sidebar.js
> fix(issuer): inactive sidebar button

- packages/new-polymath-issuer/src/pages/DividendDetails/Presenter.tsx
> fix(new-issuer): dividends detail "withdraw taxes" button overlaping

- packages/new-polymath-ui/src/components/utils/contentMappings.ts
> chore(new-ui): add thousands separator to approval for dividends

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/CsvModal.tsx
- packages/new-polymath-ui/src/components/utils/contentMappings.ts
> chore(shared): update text in transaction queue modals

- packages/polymath-issuer/src/pages/ticker/TickerPage.js
> chore(issuer): resolve typo on ticker registration page

- packages/new-polymath-issuer/src/pages/DividendsWizard/Presenter.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
Hides existing tax withholding addresses that are excluded on step 1
> feat(new-issuer): omit existing tax withholdings of exluded addresses

- packages/new-polymath-ui/src/components/utils/contentMappings.ts
> chore(new-issuer): modify text in transaction modal

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-3/index.tsx
> chore(new-issuer): add tooltip to step3 input field

- packages/new-polymath-issuer/src/components/CheckpointList/Container.tsx
- packages/new-polymath-issuer/src/components/CheckpointList/Presenter.tsx
- packages/new-polymath-issuer/src/components/DividendList/Container.tsx
- packages/new-polymath-issuer/src/components/DividendList/Presenter.tsx
Disables the Add Dividend button if any incomplete Dividends  exist
> feat(new-issuer): prevent new dividends if unfinished exist

- packages/new-polymath-issuer/src/state/sagas/requests/erc20TokenBalances.ts
This needs to be here because otherwise the DataFetcher would never return the value. The proper way to handle invalidation would be to subscribe to transfer events
> fix(new-issuer): cache balances

- packages/new-polymath-issuer/src/pages/DividendDetails/Presenter.tsx
> chore(new-issuer): change copy of dividend details transactions button

- packages/new-polymath-issuer/src/components/DividendCard/DividendCard.tsx
> fix(new-issuer): fix dividend card token name

- packages/new-polymath-issuer/src/components/enhancers/DataFetcher.tsx
Prevents unmounting of children rendered by DataFetcher on cache invalidation
> fix(new-issuer): avoid unmounting DataFetchers children on invalidation

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-3/index.tsx
> fix: set maxlength attribute on dividend title

- packages/new-polymath-issuer/src/pages/DividendDetails/Container.tsx
- packages/new-polymath-issuer/src/pages/DividendDetails/Presenter.tsx
> fix(issuer): fix link to etherscan for investor address

- packages/polymath-issuer/package.json
- packages/polymath-issuer/src/redux/modernRouterMiddleware.js
- packages/polymath-issuer/src/redux/store.js
- yarn.lock
This PR inserts a middleware to the legacy store that catches modern router push actions and translates them to legacy actions
> fix(new-issuer): handle modern internal manual redirection in legacy

- packages/new-polymath-issuer/src/pages/DividendDetails/Presenter.tsx
> fix(new-issuer): ignore excluded investors when counting withholding

- packages/new-polymath-ui/src/components/utils/contentMappings.ts
> chore(new-ui): display approval POLY spend with 2 decimals

- packages/polymath-issuer/src/actions/token.js
- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
- packages/polymath-issuer/src/pages/token/components/MintTokens.js
> fix(issuer): limit minting address count to 40

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/CsvModal.tsx
Fixes the issue [All entries deleted after user 'confirms' upload of wrong CSV on dividends step 2](https://app.asana.com/0/951808452757493/1114659192753419)
Issue is fixed by disabling the confirm button if the file contains duplicate entries, which is consistent with the behaviour of step 1.
> fix(new-issuer): fix issue with uploading csv with duplicates

- packages/new-polymath-issuer/src/components/CheckpointList/Container.tsx
- packages/new-polymath-issuer/src/components/DividendCard/DividendCard.tsx
- packages/polymath-issuer/src/redux/modernRouterMiddleware.js
- Fixes dividends distributions marked as incomplete when taxes hadn't yet been withdrawn
- Fixes issue with routing, uses the infamous double dispatch hack
> fix(issuer): incorrect disabling of new distribution button

- packages/new-polymath-shared/src/formatters/__tests__/index.ts
- packages/new-polymath-shared/src/formatters/index.ts
> fix(new-shared): update rounding method for pourcentage

- packages/polymath-issuer/src/actions/token.js
- packages/polymath-issuer/src/pages/token/components/MintTokens.js
- packages/polymath-issuer/src/reducers/token.js
Fixes the bug: [CSV Parser does not detect poorly formed CSV files](https://app.asana.com/0/951808452757493/1114644098658066)
If a file generated with Mac format, the following message will be displayed:
> fix(issuer): handle poorly formed csv

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/CsvModal.tsx
- packages/new-polymath-shared/src/utils/validators.ts
This PR:
- Fixes the numericality validator to support 0 values in the options
- Allows tax withholding percentages in the [99, 100) interval
> fix(new-shared): fix numericality validator

- packages/new-polymath-ui/src/components/TooltipIcon/styles.ts
> chore(new-ui): modify tooltipicon hover and font size

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/ConfirmModal.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
- packages/new-polymath-ui/README.md
- packages/new-polymath-ui/docs/forms.mdx
- packages/new-polymath-ui/src/components/FormItem/docs/FormItem.mdx
- packages/new-polymath-ui/src/components/inputs/CurrencySelect/CurrencySelect.tsx
> feat(new-issuer): add confirm modal when user has draft changes

- packages/new-polymath-ui/src/components/inputs/PercentageInput/PercentageInput.tsx
Fixes the bug: [No validation limit in % tax withholdings in dividends step 2](https://app.asana.com/0/951808452757493/1114871323437281)
> fix(new-ui): limit number of decimal places

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-3/index.tsx
Fixes the bug [UI allows me to proceed with an amount = 0 when creating a dividend](https://app.asana.com/0/951808452757493/1114514932327309)
> fix(new-issuer): prevent 0 amount dividends

- packages/new-polymath-issuer/src/components/DividendCard/DividendCard.tsx
> fix(new-issuer): fix remaining tax withholdings message hidden

- packages/polymath-ui/src/components/inputs/CurrencySelect/Input/index.js
Fixes the issue [Currency icons are not preloaded](https://app.asana.com/0/951808452757493/1114261649897580)
> fix(issuer): preload tpken icons

- packages/polymath-issuer/src/pages/token/components/MintTokens.js
Disables the "mint" button if the CSV file is not of the correct format.
> fix(issuer): disable mint button for invalid csv

- packages/polymath-issuer/src/actions/token.js
- packages/polymath-issuer/src/utils/parsers/index.js
Fixes the bug: [Two-digit years are parsed as 19XX instead of 20XX](https://app.asana.com/0/951808452757493/967385233474294)
> fix(issuer): handle 2 year dates in csv

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/CsvModal.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/TaxWithholdingModal.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/TaxWithholdingsTable.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
⚠️ I refactored step 2 with a separate `Form` component. This is so I could memoize the expensive filtering function.
- ~Uploading a CSV now merges the entries with existing ones instead of override~
- Adding an investor that's already on the blockchain with a percentage of 0% sets the status to `New`
- Adding an investor that's already on the blockchain with a percentage sets the status to `Updated`
- Adding an investor that's not on the blockchain sets the status to `New`
- Deleting an investor that's already on the blockchain sets the status to `Updated`
- Deleting an investor that's not on the blockchain deletes it immediately
> fix(new-issuer): refactor how status are handled

- packages/new-polymath-issuer/src/components/DividendCard/DividendCard.tsx
- packages/new-polymath-issuer/src/components/DividendList/Presenter.tsx
- packages/new-polymath-issuer/src/pages/DividendDetails/Container.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Container.tsx
- packages/new-polymath-issuer/src/routing/routes.ts
- packages/new-polymath-issuer/src/state/__tests__/selectors.ts
- packages/new-polymath-issuer/src/state/fetchers.ts
- packages/new-polymath-issuer/src/state/reducers/__tests__/__snapshots__/dataRequests.ts.snap
- packages/new-polymath-issuer/src/state/reducers/__tests__/dataRequests.ts
- packages/new-polymath-issuer/src/state/reducers/dataRequests.ts
- packages/new-polymath-issuer/src/state/sagas/procedures/checkpoints.ts
- packages/new-polymath-issuer/src/state/sagas/procedures/dividends.ts
- packages/new-polymath-issuer/src/state/sagas/requests/index.ts
- packages/new-polymath-issuer/src/state/sagas/requests/taxWithholdings.ts
- packages/new-polymath-issuer/src/types/index.ts
- packages/new-polymath-sdk/src/Polymath.ts
- packages/polymath-issuer/src/pages/dividends/DividendDetailsPage.js
- packages/polymath-issuer/src/routes.js
This PR:
- Changes the SDK function that gets tax withholdings to receive the checkpoint index as a parameter instead of using the latest checkpoint
- Changes the new-issuer request to reflect this change
- Modifies the routes and pages that use this request accordingly
> feat: use checkpoint index to fetch tax withholdings

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
> chore(new-issuer): revert back deep merging of CSV data

- packages/new-polymath-sdk/src/LowLevel/Erc20.ts
> fix(sdk): use real address to prevent reverts

- packages/polymath-js/src/contracts/Contract.js
This may fix the wrong response id error
This PR is a longshot, but it may fix the wrong response id error we get sometimes
> fix(js): increase gas multiplier

- packages/polymath-issuer/src/actions/sto.js
- packages/polymath-issuer/src/utils/contracts/index.js
This PR:
- Uses the correct address for the 2.0 CappedSTO factory
- Fixes a bug in USDTieredSTO deployment when not selecting DAI as a currency
> Fix/sto deployment 2.1 failing

- packages/new-polymath-issuer/src/pages/DividendsWizard/Presenter.tsx
Fixes the issue: [Wrong font colors in the summary component](https://app.asana.com/0/951808452757493/1115273152494335)
> chore(new-issuer): modify font color for dividends summary

- packages/polymath-js/src/contracts/STO.js
Fixes the bug [STO: dApp doesn't realize the sto is paused](https://app.asana.com/0/951808452757493/1115353146484826)
> fix(js): detect-paused-sto

- packages/new-polymath-sdk/src/LowLevel/SecurityToken.ts
Earns the title of being the shortest PR ever submitted to this repository. It fixes an off-by-one error
> fix(sdk): off-by-one error on checkpoint time retrieval

- packages/new-polymath-sdk/src/LowLevel/SecurityToken.ts
> feat(sdk): ignore archived modules when fetching

- packages/new-polymath-sdk/src/LowLevel/Erc20.ts
- packages/new-polymath-sdk/src/LowLevel/abis/NonStandardERC20Abi.ts
> fix(sdk): use non-standard erc20 abi for DAI

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
> chore(new-issuer): fix copy of next step button

- packages/new-polymath-issuer/src/components/DividendList/Presenter.tsx
- packages/new-polymath-issuer/src/components/DividendList/styles.ts
> fix(new-issuer): fix new dividends button hover and tooltips

- packages/new-polymath-issuer/src/pages/SecurityTokensDividends/Presenter.tsx
Fixes the issue [Changing dividends address while checkpoint is present doesn't change it without refresh](https://app.asana.com/0/951808452757493/1115473383222841)
> fix(new-issuer): changing diviends wallet address

- packages/new-polymath-sdk/src/LowLevel/DividendCheckpoint.ts
- packages/new-polymath-sdk/src/LowLevel/Erc20.ts
- packages/new-polymath-sdk/src/LowLevel/ModuleRegistry.ts
- packages/new-polymath-sdk/src/LowLevel/utils.ts
I wasn't able to test on Windows because I can't get the app to run on Kovan locally.
> [WIP]fix(sdk): strip out NULL chars from bytes32 string

- packages/new-polymath-issuer/src/pages/DividendsWizard/Container.tsx
Fixes the issue [Issuer can directly access URL to create dividends even if they are disabled](https://app.asana.com/0/951808452757493/1113479795804217)
> fix(new-issuer): wizard url direct access

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/TaxWithholdingModal.tsx
- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-2/index.tsx
Fixes the issue [Excluded investors can still be added/modified in the dividends step 2 page](https://app.asana.com/0/951808452757493/967385233474304)
> fix(new-issuer): adding excluded investors

- packages/new-polymath-issuer/src/pages/DividendsWizard/Container.tsx
Fixes the issue [Error when issuer tries to access a dividend checkpoint id that doesn't exist](https://app.asana.com/0/951808452757493/1116505368895676)
> fix(new-issuer): access non-existing checkpoint

- packages/new-polymath-issuer/src/pages/SecurityTokensDividends/Presenter.tsx
This PR fixes https://app.asana.com/0/951808452757493/1116637892626865
> fix(new-issuer): use proper memoization parameter for address change

- packages/new-polymath-ui/src/components/ProgressIndicator/__tests__/__snapshots__/ProgressIndicator.tsx.snap
- packages/new-polymath-ui/src/components/Table/__tests__/__snapshots__/Table.tsx.snap
- packages/new-polymath-ui/src/styles/GlobalStyles.ts
- packages/new-polymath-ui/src/styles/theme.ts
- packages/polymath-issuer/src/pages/ticker/components/ReserveTickerForm.js
- packages/polymath-issuer/src/style.scss
- packages/polymath-ui/src/components/Heading/__tests__/__snapshots__/Heading.js.snap
- packages/polymath-ui/src/deprecated/styles/globals.scss
- packages/polymath-ui/src/styles/GlobalStyles.js
- packages/polymath-ui/src/styles/theme.js
This PR also includes minor styling fixes on the /ticker page (vertical alignment of inputs).
> fix(new-ui): adjust fontweight to Stan style + remove useless fontweight

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/InvestmentTiers.js
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/TierModal.js
Fixes this issue: [Can't create an investment tier with price < 1$](https://app.asana.com/0/951808452757493/967385233474312)
> chore(issuer): update minimum value for usdsto token price

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/InvestmentTiers.js
Fixes the issue [USD Tiered STO price gets stuck at 0.01](https://app.asana.com/0/951808452757493/1116970805613916)
> fix(issuer): tiered sto price input

- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
> chore(issuer): add advisory to whitelisting

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/TierModal.js
> fix(issuer): tiered sto modal button disabling

- packages/polymath-ui/src/redux/account/actions.js
> [ISSUER-21] feat(issuer): add copy with instruction to KETH faucet

- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
- packages/polymath-issuer/src/pages/token/components/MintTokens.js
> chore: change warning copy for uploading files

- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
- packages/polymath-issuer/src/pages/token/components/MintTokens.js
- packages/polymath-ui/src/redux/account/actions.js
> Fix copy changes 

- .circleci/config.yml
> chore(issuer): change circleci config to use node10

- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
> chore(issuer): re-retrigger Azure build and deployment

- packages/polymath-issuer/src/pages/providers/data.js
> chore(issuer): fix typos

- _redirects
- packages/polymath-issuer/netlify.toml
> merge netlify changes to beta

- packages/polymath-issuer/src/pages/providers/data.js
> chore(issuer): change IBL name

- heroku.build
- package.json
- packages/polymath-issuer/Procfile
- packages/polymath-issuer/package.json
- packages/polymath-issuer/src/index.js
- packages/polymath-issuer/src/pages/providers/data.js
- yarn.lock
> Catch up Release

- packages/polymath-issuer/src/components/App.js
- packages/polymath-issuer/src/pages/home/index.js
- packages/polymath-ui/src/components/Toaster/style.scss
> chore(issuer): add toast for maintenance mode

- packages/polymath-offchain/src/routes/providers.js
Add debugging code to figure out the error returned from Sendgrid
> chore(issuer): add debugging code

- packages/polymath-offchain/src/routes/providers.js
> chore: a wider try/catch block

- packages/polymath-issuer/src/components/App.js
- packages/polymath-issuer/src/pages/home/index.js
> chore(issuer): remove maintenance notification

- packages/polymath-issuer/src/pages/compliance/components/ImportWhitelistModal.js
- packages/polymath-issuer/src/pages/token/components/MintTokens.js
- packages/polymath-issuer/src/reducers/compliance.js
- packages/polymath-issuer/src/reducers/token.js
- packages/polymath-issuer/src/utils/parsers/csv-file-validator.js
This PR disables multiple files upload for minting and whitelisting forms. "UPLOAD" button will be disabled, as long as one file is uploaded.
> chore(issuer): GT-56 (cont.): Disable multiple files upload

- packages/polymath-offchain/src/startup/setupWeb3.js
> GT-45: ensure correct ABIs are referenced

- packages/new-polymath-shared/src/constants/network.ts
- packages/polymath-shared/src/constants.js
> GT-142 change DAI address to multi-collateral contract

- packages/polymath-offchain/src/startup/setupWeb3.js
> enable emails listener in prod only

- packages/new-polymath-sdk/src/browserUtils.ts
- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
> remove deprecated functions

- packages/polymath-issuer/src/pages/account/components/ConfigCard.js
- packages/polymath-issuer/src/pages/account/index.js
> remove button from dashboard

- packages/polymath-issuer/src/pages/providers/style.scss
> fix provider tab ui

- packages/polymath-issuer/src/pages/home/index.js
> update landing page

- packages/polymath-issuer/src/pages/providers/data.js
> fix duplicate id for provider

- packages/new-polymath-ui/src/components/Footer/Footer.tsx
- packages/polymath-ui/src/components/Footer/Footer.js
- packages/polymath-ui/src/components/Footer/__tests__/__snapshots__/Footer.js.snap
- packages/polymath-ui/src/components/SignUpPage/SignUpForm.js
> fix url for tos

- packages/polymath-issuer/src/pages/sto/components/STOTemplate/Component.js
> fix sto copy

- packages/polymath-issuer/src/utils/contracts/index.js
> add signature call for 3.1.0, revert after kovan is fixed

- packages/polymath-issuer/src/utils/contracts/index.js
> filter out 3.1.0 and remove treasuryWallet

- packages/polymath-issuer/src/pages/restrictions/__tests__/RestrictionsPage.js
> disable random unit test

- packages/polymath-issuer/src/actions/account.js
- packages/polymath-issuer/src/pages/account/components/TickerCard.js
- packages/polymath-issuer/src/pages/account/index.js
- packages/polymath-js/src/contracts/SecurityTokenRegistry.js
- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
- packages/polymath-ui/src/redux/account/actions.js
> Fix ticker bug

- packages/polymath-issuer/src/pages/providers/data.js
> hotfix ids

- packages/polymath-issuer/src/pages/providers/data.js
> remove vertalo

- packages/polymath-ui/src/redux/account/actions.js
> fix infinite load screen when new user

- packages/polymath-offchain/src/utils/emails.js
> update to new emails

- packages/polymath-js/src/contracts/TransferManager.js
> GT-186: recent whitelisting event to take precedence over older ones

- packages/polymath-issuer/src/pages/providers/data.js
> add diginex

- packages/polymath-ui/src/components/EthNetworkWrapper/actions.js
- packages/polymath-ui/src/redux/account/actions.js
> add user analytics

- packages/new-polymath-issuer/package.json
- packages/new-polymath-scripts/package.json
- packages/new-polymath-sdk/package.json
- packages/new-polymath-shared/package.json
- packages/new-polymath-ui/package.json
- packages/polymath-investor/package.json
- packages/polymath-issuer/package.json
- packages/polymath-js/package.json
- packages/polymath-js/src/contracts/SecurityTokenRegistry.js
- packages/polymath-offchain/package.json
- packages/polymath-offchain/src/startup/setupDb.js
- packages/polymath-shared/package.json
- packages/polymath-ui/package.json
- yarn.lock
> update web3 and lodash, fix errors

- packages/polymath-js/src/contracts/Contract.js
> add hack for metamask 8.0+ to receive txdetails

- packages/new-polymath-sdk/src/entities/PolyTransaction.ts
> add fix for mm 8.0.4 not receiving txHash

- packages/new-polymath-issuer/src/pages/DividendsWizard/Step-3/index.tsx
- packages/new-polymath-ui/src/components/utils/contentMappings.ts
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
> remove poly from USD Tiered STO

- packages/polymath-issuer/src/pages/providers/data.js
> change diginex to digivault

- packages/new-polymath-sdk/src/entities/PolyTransaction.ts
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
- packages/polymath-issuer/src/pages/sto/components/STOTemplate/Component.js
> remove eth and expand interval

- packages/polymath-offchain/src/startup/setupWeb3.js
> Remove sto web3 listener

- packages/polymath-issuer/src/components/Dashboard.js
- packages/polymath-issuer/src/routes.js
> undo previous commits

- packages/polymath-issuer/src/actions/token.js
- packages/polymath-issuer/src/pages/sto/components/SelectSTOTemplate.js
- packages/polymath-issuer/src/pages/token/components/CompleteTokenForm.js
- packages/polymath-issuer/src/pages/token/components/MintTokens.js
> add copy changes

- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
> remove eth as default

- packages/polymath-issuer/src/pages/home/index.js
> add copy for usage fees

- packages/polymath-issuer/src/pages/home/index.js
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
> Add usage fees

- packages/polymath-issuer/src/pages/home/index.js
- packages/polymath-issuer/src/pages/sto/components/ConfigureSTOForm/forms/USDTieredSTO/index.js
> Fix usage fees
